// Supabase Edge Function: promptpay-webhook
// รับ webhook จาก Payment Gateway ไทย (Omise / GB Prime Pay) เมื่อชำระ PromptPay สำเร็จ
// → อัปเดต subscription.status = 'active' ในเวิร์กสเปซที่อ้างถึง (ใช้ service role)
// → ส่งอีเมลยืนยันการชำระเงินผ่าน Resend API
//
// Deploy:  supabase functions deploy promptpay-webhook --no-verify-jwt
// Secrets: supabase secrets set WEBHOOK_SECRET=...
//          supabase secrets set RESEND_API_KEY=re_xxxxxxxxxxxx
//
// ตั้ง URL นี้เป็น webhook endpoint ใน Omise/GB Prime และส่ง metadata.workspace_id มาด้วย

import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const WEBHOOK_SECRET = Deno.env.get("WEBHOOK_SECRET") ?? "";
const ADMIN_EMAIL = "support@b-tctraining.com";
const FROM_EMAIL = "CEO AI Thailand <noreply@ceoaithailand.org>";

// ─── Resend helper ────────────────────────────────────────────────────────────
async function sendMail(to: string, subject: string, html: string): Promise<void> {
  const key = Deno.env.get("RESEND_API_KEY");
  if (!key) return;
  await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { "Authorization": `Bearer ${key}`, "Content-Type": "application/json" },
    body: JSON.stringify({ from: FROM_EMAIL, to: [to], subject, html }),
  }).catch(() => {}); // fire-and-forget
}

async function getUserEmail(admin: ReturnType<typeof createClient>, wsId: string): Promise<string | null> {
  try {
    const { data } = await admin.auth.admin.getUserById(wsId);
    return data?.user?.email ?? null;
  } catch { return null; }
}

function paymentConfirmedHtml(plan: string, amount: number, wsId: string): string {
  const planLabel = plan === "growth" ? "Growth ฿1,490/เดือน" : plan === "scale" ? "Scale ฿5,900/เดือน" : plan;
  return `
<div style="font-family:Kanit,sans-serif;max-width:560px;margin:auto;background:#0f172a;color:#f8fafc;padding:32px;border-radius:12px">
  <h2 style="color:#06b6d4;margin-top:0">✅ ยืนยันการชำระเงินสำเร็จ</h2>
  <p>ขอบคุณสำหรับการชำระเงิน! แพ็กเกจ <strong style="color:#06b6d4">${planLabel}</strong> ของคุณเปิดใช้งานแล้ว</p>
  <table style="width:100%;border-collapse:collapse;margin:16px 0">
    <tr><td style="padding:8px;color:#94a3b8">แพ็กเกจ</td><td style="padding:8px;font-weight:600">${planLabel}</td></tr>
    <tr><td style="padding:8px;color:#94a3b8">จำนวนเงิน</td><td style="padding:8px;font-weight:600">฿${amount.toLocaleString()}</td></tr>
    <tr><td style="padding:8px;color:#94a3b8">Workspace ID</td><td style="padding:8px;font-family:monospace;font-size:12px">${wsId}</td></tr>
  </table>
  <p style="color:#94a3b8;font-size:13px">ระบบจะต่ออายุอัตโนมัติทุกเดือน หากต้องการยกเลิกหรือเปลี่ยนแพ็ก ติดต่อ <a href="mailto:${ADMIN_EMAIL}" style="color:#06b6d4">${ADMIN_EMAIL}</a></p>
  <p style="color:#64748b;font-size:12px;margin-top:24px">CEO AI Thailand · แพลตฟอร์มสร้างบริษัท AI อัตโนมัติสำหรับธุรกิจไทย</p>
</div>`;
}

function adminNotifyHtml(plan: string, amount: number, wsId: string, userEmail: string | null): string {
  return `
<div style="font-family:sans-serif;max-width:480px;margin:auto">
  <h3>💳 Payment Received</h3>
  <p><b>Plan:</b> ${plan} | <b>Amount:</b> ฿${amount}</p>
  <p><b>Workspace:</b> <code>${wsId}</code></p>
  ${userEmail ? `<p><b>User Email:</b> ${userEmail}</p>` : ""}
  <p style="color:#64748b;font-size:12px">Auto-generated by promptpay-webhook</p>
</div>`;
}

// ─── Handler ──────────────────────────────────────────────────────────────────
Deno.serve(async (req) => {
  if (req.method !== "POST") return new Response("method_not_allowed", { status: 405 });

  const secret = req.headers.get("x-webhook-secret") ?? new URL(req.url).searchParams.get("secret") ?? "";
  if (WEBHOOK_SECRET && secret !== WEBHOOK_SECRET) return new Response("forbidden", { status: 403 });

  let evt: any;
  try { evt = await req.json(); } catch { return new Response("bad_json", { status: 400 }); }

  const charge = evt?.data ?? evt?.charge ?? evt;
  const paid = charge?.status === "successful" || charge?.paid === true || charge?.resultCode === "00";
  const workspaceId = charge?.metadata?.workspace_id ?? evt?.metadata?.workspace_id;
  const planId = charge?.metadata?.plan_id ?? "growth";

  if (!paid) return new Response("ignored", { status: 200 });
  if (!workspaceId) return new Response("missing_workspace_id", { status: 400 });

  const admin = createClient(SUPABASE_URL, SERVICE_ROLE);

  const { data: row, error: selErr } = await admin
    .from("workspace_state").select("data").eq("workspace_id", workspaceId).maybeSingle();
  if (selErr) return new Response("db_error", { status: 500 });

  const PLAN_PRICE: Record<string, number> = { free: 0, growth: 1490, scale: 5900 };
  const paidAmount: number =
    (typeof charge?.amount === "number" ? charge.amount / 100 : 0) ||
    (PLAN_PRICE[planId] ?? 0);

  const state = (row?.data ?? {}) as Record<string, any>;
  const sub = state.subscription ?? {};

  const existingInvoices: any[] = sub.invoices ?? [];
  let markedPending = false;
  for (const inv of existingInvoices) {
    if (inv.status === "pending" && inv.plan === planId) {
      inv.status = "paid";
      inv.amount = paidAmount || inv.amount;
      markedPending = true;
      break;
    }
  }
  if (!markedPending) {
    existingInvoices.unshift({
      id: "inv-" + Date.now().toString(36),
      date: new Date().toISOString(),
      plan: planId,
      amount: paidAmount,
      status: "paid",
    });
  }

  state.subscription = {
    ...sub,
    plan: planId,
    status: "active",
    invoices: existingInvoices,
    currentPeriodEnd: (() => {
      const d = new Date(); d.setMonth(d.getMonth() + 1); return d.toISOString();
    })(),
  };

  const { error: upErr } = await admin
    .from("workspace_state")
    .upsert({ workspace_id: workspaceId, data: state, updated_at: new Date().toISOString() }, { onConflict: "workspace_id" });
  if (upErr) return new Response("db_error", { status: 500 });

  // ─── ส่งอีเมลยืนยัน ────────────────────────────────────────────────────
  const userEmail = await getUserEmail(admin, workspaceId);
  await Promise.all([
    userEmail
      ? sendMail(userEmail, `✅ ยืนยันการชำระเงิน — แพ็ก ${planId} CEO AI Thailand`, paymentConfirmedHtml(planId, paidAmount, workspaceId))
      : Promise.resolve(),
    sendMail(ADMIN_EMAIL, `[CEO AI] Payment ฿${paidAmount} — ${planId} — ${workspaceId.slice(0, 8)}`, adminNotifyHtml(planId, paidAmount, workspaceId, userEmail)),
  ]);

  return new Response(JSON.stringify({ ok: true, workspace_id: workspaceId, plan: planId, amount: paidAmount }), {
    status: 200, headers: { "content-type": "application/json" },
  });
});
