import type { AppData } from './types';

export const DEFAULT_DATA: AppData = {
  stages: [
    {
      id: 's1',
      label: 'ค้นหา',
      title: 'ค้นหาคำตอบ (Trigger)',
      emotion: 'กดดัน — รู้ว่ามีปัญหา แต่ยังไม่รู้ว่าต้องการอะไร',
      touch: [
        "Google: 'วิธีแก้ปัญหาต้นทุนสูง SME'",
        'LinkedIn Article จากที่ปรึกษา',
        'Facebook Group ธุรกิจ / เพื่อนแนะนำ',
        'YouTube: case study ธุรกิจไทย',
      ],
      action: [
        'ค้นหาข้อมูลช่วงดึก หลังเลิกงาน',
        'Save บทความที่ตอบโจทย์ปัญหาตัวเอง',
        'ส่งลิงก์ให้ CFO หรือทีม Ops ดู',
      ],
      pain: [
        'บทความส่วนใหญ่เป็นทฤษฎี ไม่พูดถึงธุรกิจจริงๆ',
        'ไม่รู้ว่าต้องการ consultant หรือแค่ซอฟต์แวร์',
      ],
      opp: [
        'เขียน blog ที่ระบุ industry และขนาดทีมชัดเจน',
        "ทำ 'เช็คลิสต์วินิจฉัยปัญหา' ให้ผู้อ่านทดสอบตัวเอง",
      ],
    },
    {
      id: 's2',
      label: 'พบเรา',
      title: 'พบบริษัทเราครั้งแรก (Discovery)',
      emotion: 'สนใจแต่ยังสงสัย — เจอหลายเจ้าพร้อมกัน',
      touch: [
        'Google Organic (SEO): หน้า Services',
        'LinkedIn Company Page + โพสต์ที่แชร์',
        'Blog / Insight article ที่ rank ใน Google',
        'Lead magnet: E-book หรือ Template ฟรี',
      ],
      action: [
        'อ่านหน้า About และ Services',
        'ดู Case study หรือผลงาน',
        'ตรวจสอบว่าเคยทำ industry เดียวกันไหม',
        'Download E-book หรือ Template ฟรี',
      ],
      pain: [
        'หน้าเว็บพูดถึงบริษัท ไม่ได้พูดถึงปัญหาลูกค้า',
        'ไม่มี case study ที่ตรงกับ industry หรือขนาด',
      ],
      opp: [
        'เปลี่ยน Hero section ให้พูดถึงปัญหาลูกค้าก่อน',
        'เพิ่ม case study แยก tag ตาม industry',
      ],
    },
    {
      id: 's3',
      label: 'ประเมิน',
      title: 'เปรียบเทียบและประเมิน (Consideration)',
      emotion: 'ลังเล — กลัวจ้างแล้วไม่ได้ผล เสียเงินฟรี',
      touch: [
        'หน้า Services + Pricing (ถ้ามี)',
        'Google Reviews / Testimonials',
        'LinkedIn: ดูโปรไฟล์ที่ปรึกษาแต่ละคน',
        'เปรียบเทียบกับ consultant อื่น 2–3 เจ้า',
      ],
      action: [
        'อ่าน testimonial และ review อย่างละเอียด',
        'ถามเพื่อนที่เคยจ้าง consultant',
        'Shortlist เหลือ 2–3 เจ้า',
        'หารือกับหุ้นส่วนหรือ CFO ก่อนติดต่อ',
      ],
      pain: [
        'ไม่มีราคาบนเว็บ ต้องติดต่อก่อนถึงจะรู้',
        'Testimonial กว้างเกินไป ไม่บอกว่าแก้อะไรได้จริง',
      ],
      opp: [
        "เพิ่ม 'ผลลัพธ์ที่ลูกค้า SME ได้รับ' พร้อมตัวเลข",
        'ทำ pricing tier คร่าวๆ เพื่อลด friction',
      ],
    },
    {
      id: 's4',
      label: 'ติดต่อ',
      title: 'ติดต่อครั้งแรก (First Contact)',
      emotion: 'กล้าแล้ว — แต่ยังต้องการความมั่นใจอีกนิด',
      touch: [
        'Contact form บนเว็บ',
        'ส่ง DM ใน LinkedIn',
        'กรอก Form จาก Lead magnet',
        'โทรตรง (พบน้อยกว่า)',
      ],
      action: [
        'กรอก contact form หรือส่ง email',
        'เขียนอธิบายปัญหาสั้นๆ',
        'รอ response — ถ้าช้าจะเสียความสนใจ',
        'Follow up ใน LinkedIn ถ้าไม่มีใครตอบ',
      ],
      pain: [
        'Response time ช้าทำให้ไปคุยกับเจ้าอื่นก่อน',
        'ไม่รู้ว่าควรเตรียมข้อมูลอะไรไปคุย',
      ],
      opp: [
        'ตั้ง auto-reply ทันทีพร้อมบอก timeline',
        "ส่ง 'เตรียมตัวก่อนนัดคุย' guide ทันทีหลังรับ lead",
      ],
    },
    {
      id: 's5',
      label: 'Discovery',
      title: 'Discovery Call / Meeting',
      emotion: 'ตื่นเต้น — อยากรู้ว่าเราจะช่วยได้จริงไหม',
      touch: [
        'Zoom / Teams Meeting (30–60 นาที)',
        'Diagnostic questionnaire ก่อนประชุม',
        'Presentation / Workshop เล็กๆ',
        'Proposal outline เบื้องต้น',
      ],
      action: [
        'เล่าปัญหาและ context ของธุรกิจ',
        'ถามเรื่อง approach และ timeline',
        'ถามเรื่องค่าใช้จ่ายคร่าวๆ',
        'เอาไปคุยต่อกับทีมหรือหุ้นส่วน',
      ],
      pain: [
        'ที่ปรึกษาพูดถึง framework มากเกินไป ไม่ฟัง pain',
        'ไม่รู้ว่าจะได้ผลลัพธ์อะไรชัดเจน',
      ],
      opp: [
        'ใช้ 80% ของเวลาในการถามและฟัง',
        "สรุป 'สิ่งที่เราได้ยิน' ก่อนเสนอ solution",
      ],
    },
    {
      id: 's6',
      label: 'ตัดสินใจ',
      title: 'ตัดสินใจ (Decision)',
      emotion: 'กังวลสูงสุด — ROI ไม่ชัด กลัวเสียเงินเปล่า',
      touch: [
        'Proposal / Scope of Work',
        'Presentation ต่อหุ้นส่วน',
        'Contract + Payment Terms',
        'อ้างอิง reference ลูกค้าเก่า',
      ],
      action: [
        'อ่าน proposal อย่างละเอียด',
        'ขอปรับ scope หรือราคา',
        'ให้ CFO / ทนายตรวจสัญญา',
        'เซ็น + โอนมัดจำ',
      ],
      pain: [
        'Proposal ดู generic เหมือนส่งให้ทุกคน',
        'ROI ไม่ชัดเจน ทำให้ justify กับหุ้นส่วนยาก',
      ],
      opp: [
        'ทำ proposal ที่ใช้ภาษาและตัวเลขของลูกค้า',
        'เพิ่ม ROI scenario หรือ success metric ที่ measurable',
      ],
    },
    {
      id: 's7',
      label: 'ดำเนินงาน',
      title: 'ดำเนินโครงการ (Delivery)',
      emotion: 'ตั้งความหวังสูง — เริ่มนับถอยหลังถึงผลลัพธ์',
      touch: [
        'Kick-off Workshop',
        'รายงานรายเดือน + Dashboard',
        'Monthly check-in call',
        'Deliverable: แผน / Framework / Playbook',
      ],
      action: [
        'เข้าร่วม workshop และ session',
        'ให้ข้อมูลและ access ที่จำเป็น',
        'ติดตาม milestones กับทีมภายใน',
        'นำแผนไป implement',
      ],
      pain: [
        'ทีมภายในไม่มีเวลา implement ตามแผน',
        'ผลลัพธ์เห็นช้า ทำให้ความมั่นใจลดลง',
      ],
      opp: [
        'กำหนด quick win ภายใน 30 วันแรก',
        'Check-in สั้นๆ ทุกสัปดาห์แทนรายงานหนักๆ',
      ],
    },
    {
      id: 's8',
      label: 'รักษา',
      title: 'รักษาความสัมพันธ์ (Retention)',
      emotion: 'พึงพอใจ — พร้อมแนะนำต่อถ้าเราดูแลดีพอ',
      touch: [
        'Quarterly Review',
        'Upsell / ต่อสัญญา',
        'Case study ร่วมกัน',
        'Referral / แนะนำเพื่อน MD',
      ],
      action: [
        'ทบทวนผลลัพธ์กับที่ปรึกษา',
        'แนะนำบริษัทให้ MD คนอื่นใน network',
        'ให้ testimonial หรือ review',
        'ต่อสัญญาในโปรเจกต์ถัดไป',
      ],
      pain: [
        'ความสัมพันธ์ห่างลงหลังโปรเจกต์จบ',
        'ไม่รู้ว่ามีบริการอื่นที่จะช่วยได้อีก',
      ],
      opp: [
        'ส่ง insight ที่เกี่ยวข้องกับธุรกิจเขาทุกเดือน',
        'ชวนเป็น featured case study แลกกับ referral privilege',
      ],
    },
  ],
  personas: [
    {
      name: 'คุณกมล',
      role: 'MD / เจ้าของธุรกิจ · ทีม 30 คน',
      initials: 'KP',
      bg: '#dbeafe',
      tc: '#1e40af',
      quote: '"รู้ว่ามีปัญหา แต่ไม่มีเวลาหาทางแก้ — ต้องการคนที่มาช่วยวางแผนและทำให้เป็นจริงได้"',
      goal: [
        'อยากเห็น revenue growth หรือลดต้นทุนชัดเจน',
        'ต้องการ consultant ที่ลงมือได้จริง',
        'อยากได้ผลลัพธ์เร็ว ไม่อยากรอเป็นปี',
      ],
      fear: [
        'กังวลว่าเสียเงินแล้วไม่ได้ผล',
        'ไม่มีเวลาติดตามงานตลอด',
        'ไม่แน่ใจว่า consultant เข้าใจธุรกิจจริงๆ',
      ],
      search: [
        "Google: 'ที่ปรึกษาธุรกิจ SME ไทย'",
        'LinkedIn article เรื่อง strategy',
        'Podcast / YouTube ธุรกิจ',
      ],
      action: [
        'ตัดสินใจคนเดียวหรือปรึกษาหุ้นส่วน',
        'อ่านรีวิวและดู case study ก่อนติดต่อ',
        'นัด discovery call ในเวลาว่าง',
      ],
    },
    {
      name: 'คุณนภา',
      role: 'CFO / Finance Director · รายงานต่อ MD',
      initials: 'NP',
      bg: '#fef9c3',
      tc: '#854d0e',
      quote: '"ต้องการตัวเลขชัดเจนก่อนอนุมัติงบ — ROI คืออะไร และจะวัดได้อย่างไร?"',
      goal: [
        'Business case ที่ defend ต่อ board ได้',
        'Cost-benefit analysis ละเอียด',
        'Milestone และ payment term ชัดเจน',
      ],
      fear: [
        'ถูกตำหนิถ้าโปรเจกต์ไม่คุ้มค่า',
        'Scope creep ที่ทำให้ต้นทุนเกิน budget',
        'ไม่มี exit clause ถ้างานไม่ได้คุณภาพ',
      ],
      search: [
        'ไม่ค้นหาเอง — รับข้อมูลจาก MD',
        'อ่าน proposal และ contract อย่างละเอียด',
        "อาจค้นหา: 'consultant fee structure B2B'",
      ],
      action: [
        'ตรวจ proposal และ contract ทุกบรรทัด',
        'ขอ reference จากลูกค้าเก่า',
        'เสนอแก้ payment terms ก่อนเซ็น',
      ],
    },
    {
      name: 'คุณธีร์',
      role: 'Operations Manager · ทีม 15 คน',
      initials: 'TP',
      bg: '#dcfce7',
      tc: '#166534',
      quote: '"เป็นคนที่ต้อง implement จริงๆ — ถ้าแผนทำตามไม่ได้จริงในทีม ก็ไม่มีประโยชน์"',
      goal: [
        'Process ที่ทีมทำตามได้จริง',
        'Tool และ template ที่ใช้ได้ทันที',
        'ให้ที่ปรึกษาลงมาคุยกับทีมจริงๆ',
      ],
      fear: [
        'แผนสวยแต่ทำไม่ได้จริงใน operation',
        'ที่ปรึกษาไม่เข้าใจ day-to-day ของทีม',
        'เปลี่ยนแปลงเร็วเกินไปทำให้ทีม resist',
      ],
      search: [
        'ไม่ได้อยู่ในการค้นหาเริ่มต้น',
        'เข้ามาใน loop หลัง MD ตัดสินใจแล้ว',
        "อาจค้นหา: 'OKR template', 'process improvement'",
      ],
      action: [
        'เข้าร่วม kick-off และ workshop',
        'เป็น point of contact หลักระหว่างโปรเจกต์',
        'ทดสอบ framework กับทีมก่อน roll out',
      ],
    },
  ],
  contentPlan: [
    {
      label: 'เดือน 1 — Awareness',
      goal: 'เป้าหมาย: ดึงลูกค้าใหม่จาก Google และ LinkedIn ให้รู้จักเราในฐานะ thought leader ที่เข้าใจ SME จริงๆ',
      cols: [
        { hd: 'Blog / SEO (2 บทความ)', color: '#1a4f8a', items: ["'5 สัญญาณที่บอกว่า SME ต้องการ strategy consultant'", "'ทำไมโรงงานขนาดกลางถึงขาดทุนโดยไม่รู้ตัว'", 'Keyword: ที่ปรึกษาธุรกิจ SME, ลดต้นทุนโรงงาน'] },
        { hd: 'LinkedIn (8 โพสต์)', color: '#1c1814', items: ['Case study mini: สิ่งที่เรียนรู้จากลูกค้า 30 ราย', 'Insight: ตัวเลขน่าสนใจเกี่ยวกับ SME ไทย', 'Behind the scene: วิธีทำงานของทีม', 'Poll: ปัญหาใดที่ทีมคุณเจอบ่อยที่สุด?'] },
        { hd: 'Lead Magnet (1 ชิ้น)', color: '#2d6a4f', items: ["Template: 'เช็คลิสต์วินิจฉัยปัญหาองค์กร 20 ข้อ'", 'เก็บ email เพื่อ nurture ต่อ', 'แจกฟรีบน Landing page + LinkedIn'] },
        { hd: 'KPI เดือน 1', color: '#a05c1a', items: ['Organic traffic +20%', 'LinkedIn follower +50', 'Lead magnet download 30+ ราย', 'Discovery call request 3–5 ราย'] },
      ],
    },
    {
      label: 'เดือน 2 — Nurture',
      goal: 'เป้าหมาย: เปลี่ยน lead ที่รู้จักเราให้เข้าใจว่าเราแก้ปัญหาได้จริง และลด friction ก่อนติดต่อ',
      cols: [
        { hd: 'Blog / SEO (2 บทความ)', color: '#1a4f8a', items: ["'เลือก Strategy Consultant อย่างไรไม่ให้เสียเงินเปล่า'", 'Case study: บริษัทผลิตชิ้นส่วน ลดต้นทุน 18% ใน 90 วัน', 'Keyword: เปรียบเทียบที่ปรึกษาธุรกิจ'] },
        { hd: 'Email Nurture (3 ฉบับ)', color: '#1c1814', items: ["ฉบับ 1: ส่ง case study ที่ตรง industry", "ฉบับ 2: FAQ — 'ถามมากที่สุดก่อนจ้างเรา'", 'ฉบับ 3: เชิญ discovery call พร้อม calendar link'] },
        { hd: 'LinkedIn (8 โพสต์)', color: '#2d6a4f', items: ['Testimonial พร้อม quote จากลูกค้าจริง', "'3 คำถามที่ควรถาม consultant ก่อนจ้าง'", 'Video: walk-through วิธีทำงาน 3 นาที', 'Repost บทความ engagement สูงจากเดือน 1'] },
        { hd: 'KPI เดือน 2', color: '#a05c1a', items: ['Email open rate >40%', 'Case study page view 200+', 'Discovery call +30% จากเดือน 1', 'Proposal sent 3+ ชุด'] },
      ],
    },
    {
      label: 'เดือน 3 — Convert',
      goal: 'เป้าหมาย: ปิด deal และสร้างระบบที่ทำให้ลูกค้าเก่า refer ลูกค้าใหม่ให้เราต่อเนื่อง',
      cols: [
        { hd: 'Sales Content', color: '#1a4f8a', items: ['Proposal template ที่มี ROI scenario ชัดเจน', "One-pager: 'ผลลัพธ์ที่ SME ของคุณจะได้รับ'", 'FAQ สำหรับ CFO / หุ้นส่วน'] },
        { hd: 'Blog / SEO (1 บทความ)', color: '#1c1814', items: ["'ROI ของการจ้าง Strategy Consultant คำนวณอย่างไร'", 'Keyword: ค่าที่ปรึกษาธุรกิจ, ROI consultant'] },
        { hd: 'Retention Content', color: '#2d6a4f', items: ['Monthly insight email สำหรับลูกค้าปัจจุบัน', 'QBR deck template ที่ช่วยสรุปผลลัพธ์', "Referral card: 'แนะนำเพื่อน MD รับ session ฟรี 1 ครั้ง'"] },
        { hd: 'KPI เดือน 3', color: '#a05c1a', items: ['Proposal-to-close rate >30%', 'Referral lead 1–2 ราย', 'Retention rate >80%', 'MRR growth จาก upsell'] },
      ],
    },
  ],
  actions: [
    { done: false, title: 'ทำ Case Study แยก Industry พร้อมตัวเลขจริง', desc: "ลูกค้า SME ไม่เชื่อ testimonial ทั่วไป — ต้องการธุรกิจที่ใกล้เคียงและผลลัพธ์จับต้องได้ เช่น 'ลดต้นทุน 18% ใน 90 วัน สำหรับโรงงานทีม 40 คน'", priority: 1, nb: '#fdf3f0', nt: '#c44b2b', tags: [{ label: 'Impact สูง', className: 't-impact' }, { label: 'Effort ต่ำ', className: 't-effort' }, { label: 'ประเมิน', className: 't-stage' }, { label: 'ตัดสินใจ', className: 't-stage' }] },
    { done: false, title: 'เพิ่ม ROI Calculator บน Proposal', desc: 'ช่วงตัดสินใจคือ pain สูงสุด — proposal ที่มีตัวเลข ROI ชัดเจนช่วยลด friction ได้มาก ลูกค้าต้องเอาไป justify กับหุ้นส่วนและ CFO', priority: 2, nb: '#fdf6ec', nt: '#a05c1a', tags: [{ label: 'Impact สูง', className: 't-impact' }, { label: 'Effort กลาง', className: 't-effort' }, { label: 'ตัดสินใจ', className: 't-stage' }] },
    { done: false, title: "ตั้ง Auto-reply + 'คู่มือเตรียมตัวก่อนนัดคุย'", desc: 'Inbound lead ที่รอ response นานกว่า 4 ชั่วโมงมักเสียความสนใจ ส่ง guide สั้นๆ ทันทีสร้าง trust และช่วยให้ discovery call มีคุณภาพขึ้น', priority: 2, nb: '#fdf6ec', nt: '#a05c1a', tags: [{ label: 'Impact สูง', className: 't-impact' }, { label: 'Effort ต่ำ', className: 't-effort' }, { label: 'ติดต่อ', className: 't-stage' }] },
    { done: false, title: "เพิ่ม 'เช็คลิสต์วินิจฉัยปัญหา' บน Blog", desc: 'ลูกค้า SME ช่วง Trigger ยังไม่แน่ใจว่าต้องการ consultant — tool ง่ายๆ ที่ช่วย self-qualify เพิ่มโอกาสที่เขาจะติดต่อมาพร้อมความตั้งใจสูง', priority: 3, nb: '#f5f0e8', nt: '#4a453e', tags: [{ label: 'Impact กลาง', className: 't-impact' }, { label: 'Effort ต่ำ', className: 't-effort' }, { label: 'ค้นหา', className: 't-stage' }, { label: 'พบเรา', className: 't-stage' }] },
    { done: false, title: 'กำหนด Quick Win 30 วันแรกใน Onboarding', desc: 'ลูกค้าที่เพิ่งเซ็นสัญญาต้องการเห็นผลลัพธ์เร็ว ระบุ deliverable ชิ้นแรกที่จับต้องได้ภายใน 4 สัปดาห์เพื่อรักษา momentum', priority: 3, nb: '#f5f0e8', nt: '#4a453e', tags: [{ label: 'Impact กลาง', className: 't-impact' }, { label: 'Effort กลาง', className: 't-effort' }, { label: 'ดำเนินงาน', className: 't-stage' }] },
    { done: false, title: 'สร้าง Referral Program สำหรับ MD Network', desc: 'ลูกค้าที่พึงพอใจมี referral intent สูง แต่มักไม่ทำเพราะไม่มี mechanism ง่ายๆ incentive เล็กน้อยหรือ co-case study เปิด loop นี้ได้', priority: 3, nb: '#f5f0e8', nt: '#4a453e', tags: [{ label: 'Impact สูง', className: 't-impact' }, { label: 'Effort กลาง', className: 't-effort' }, { label: 'รักษา', className: 't-stage' }] },
  ],
  funnel: [
    { stageId: 's1', leads: 10000, note: 'ผู้เข้าชมเนื้อหา / Google Organic' },
    { stageId: 's2', leads: 2500,  note: 'คลิกเข้าเว็บ / อ่านบทความ' },
    { stageId: 's3', leads: 750,   note: 'อ่าน Services / ดู Case Study' },
    { stageId: 's4', leads: 225,   note: 'กรอก Contact Form / ส่ง DM' },
    { stageId: 's5', leads: 135,   note: 'นัด Discovery Call สำเร็จ' },
    { stageId: 's6', leads: 81,    note: 'ได้รับ Proposal / อยู่ระหว่างพิจารณา' },
    { stageId: 's7', leads: 57,    note: 'เซ็นสัญญา เริ่มโปรเจกต์' },
    { stageId: 's8', leads: 40,    note: 'ต่อสัญญา / ลูกค้าประจำ' },
  ],
  roi: {
    avgDealValue: 150000,
    teamHourlyRate: 1500,
    monthlyRevenueTarget: 1500000,
    stageCosts: [
      { stageId: 's1', hours: 40 },
      { stageId: 's2', hours: 20 },
      { stageId: 's3', hours: 30 },
      { stageId: 's4', hours: 25 },
      { stageId: 's5', hours: 15 },
      { stageId: 's6', hours: 20 },
      { stageId: 's7', hours: 10 },
      { stageId: 's8', hours: 8 },
    ],
  },
  businessModel: {
    bmc: {
      partners: [
        'Digital Marketing Agency',
        'Platform: LinkedIn, Google Ads',
        'ผู้เชี่ยวชาญเฉพาะทาง (Finance, IT, Legal)',
      ],
      activities: [
        'Strategy Consulting & Workshop',
        'Inbound Content Marketing',
        'Discovery & Proposal Process',
        'Client Success & Quarterly Review',
      ],
      value: [
        'แก้ปัญหา SME ไทยเฉพาะกลุ่ม',
        'ผลลัพธ์วัดได้ภายใน 90 วัน',
        'ที่ปรึกษาที่ลงมือได้จริง ไม่แค่แผน',
        'เข้าใจ context ธุรกิจไทยในเชิงลึก',
      ],
      relationships: [
        'Discovery Call ส่วนตัว 1:1',
        'Monthly Check-in & Progress Report',
        'Quarterly Business Review (QBR)',
        'Insight Email รายเดือน',
      ],
      segments: [
        'MD / เจ้าของ SME ทีม 10–100 คน',
        'CFO / Finance Director',
        'Operations Manager',
      ],
      resources: [
        'ทีมที่ปรึกษาประสบการณ์ 10+ ปี',
        'Methodology & Framework IP',
        'Case Study Library (30+ ราย)',
        'MD Network & Referral Base',
      ],
      channels: [
        'Google Organic / SEO Blog',
        'LinkedIn Company Page & Posts',
        'Lead Magnet / E-book ฟรี',
        'Referral จากลูกค้าเก่า',
      ],
      costs: [
        'ค่าแรงทีม Consultant',
        'Digital Marketing & Content Production',
        'Software & Cloud Tools',
        'Travel, Venue & Events',
      ],
      revenue: [
        'Project-based Consulting Fee',
        'Monthly Retainer',
        'Workshop & Training Fee',
        'Online Course / Digital Product',
      ],
    },
    de24: Array.from({ length: 24 }, () => ({ done: false, notes: '' })),
  },
  aiCompany: {
    name: 'บริษัท AI ของฉัน',
    goal: 'เพิ่มยอดขายออนไลน์ของธุรกิจให้ถึง ฿500,000/เดือน ภายใน 90 วัน โดยใช้ทีม AI ทำงานแทน',
    industry: 'อีคอมเมิร์ซ / สินค้าไลฟ์สไตล์',
    running: false,
    heartbeatSec: 600,
    autoHire: false,
    agents: [
      {
        id: 'a-ceo', role: 'CEO', name: 'อาทิตย์', avatar: '🧭', color: '#c44b2b',
        mandate: 'รับเป้าหมายหลักจากบอร์ด วิเคราะห์ วางแผน จ้างทีม และมอบหมายงาน',
        model: 'claude-opus-4-8', status: 'working', reportsTo: null,
      },
      {
        id: 'a-cto', role: 'CTO', name: 'ธารา', avatar: '⚙️', color: '#1a4f8a',
        mandate: 'ดูแลระบบ เชื่อมต่อ API เครื่องมือภายนอก และทำงานอัตโนมัติให้เสถียร',
        model: 'claude-sonnet-4-6', status: 'working', reportsTo: 'a-ceo',
      },
      {
        id: 'a-cmo', role: 'CMO', name: 'มณี', avatar: '📣', color: '#2d6a4f',
        mandate: 'วางแผนการตลาด คอนเทนต์ และแคมเปญหาลูกค้าใหม่ผ่านช่องทางออนไลน์',
        model: 'claude-sonnet-4-6', status: 'idle', reportsTo: 'a-ceo',
      },
    ],
    tasks: [
      { id: 't1', agentId: 'a-cmo', title: 'ร่างแคมเปญเปิดตัวสินค้าใหม่บน Facebook', detail: 'กำหนดกลุ่มเป้าหมาย งบ และข้อความโฆษณา 3 เวอร์ชัน', status: 'in_progress' },
      { id: 't2', agentId: 'a-cto', title: 'เชื่อม Brave Search API เพื่อวิเคราะห์คู่แข่ง', detail: 'ดึงราคาและรีวิวคู่แข่ง 5 ราย', status: 'queued' },
      { id: 't4', agentId: 'a-cmo', title: 'ตรวจร่างอีเมลนิวส์เลตเตอร์ก่อนส่ง', detail: 'รอบอร์ด/CEO รีวิวก่อนยิงจริง', status: 'review' },
      { id: 't3', agentId: 'a-ceo', title: 'สรุปแผนรายสัปดาห์เสนอบอร์ด', detail: 'รวมความคืบหน้าและของบอนุมัติ', status: 'done' },
    ],
    approvals: [
      { id: 'ap1', agentId: 'a-cmo', title: 'อนุมัติงบยิงแอด Facebook ฿15,000', detail: 'แคมเปญเปิดตัวสินค้าใหม่ คาดได้ลูกค้า ~120 ราย', impact: 'งบ ฿15,000', status: 'pending' },
      { id: 'ap2', agentId: 'a-cto', title: 'อนุมัติสมัครเครื่องมือ Email อัตโนมัติ', detail: 'ค่าบริการ ฿590/เดือน เพื่อส่งอีเมลติดตามลูกค้า', impact: 'งบ ฿590/เดือน', status: 'pending' },
    ],
    integrations: [
      { id: 'in-search', name: 'Brave Search API', desc: 'ให้เอเจนต์ค้นคว้าข้อมูลตลาด คู่แข่ง และข่าวสารแบบเรียลไทม์', icon: '🔎', connected: false, apiKey: '' },
      { id: 'in-email', name: 'Resend (Email API)', desc: 'ส่งอีเมล รายงาน และนิวส์เลตเตอร์หาลูกค้าโดยอัตโนมัติ', icon: '✉️', connected: false, apiKey: '' },
      { id: 'in-line', name: 'LINE Messaging API', desc: 'ตอบแชทและส่งข้อความหาลูกค้าผ่าน LINE Official Account', icon: '💬', connected: false, apiKey: '' },
      { id: 'in-sheet', name: 'Google Sheets', desc: 'บันทึกผลงานและรายงานลงสเปรดชีตอัตโนมัติ', icon: '📊', connected: false, apiKey: '' },
    ],
    purchasedSkills: [],
    skillXP: 0,
    mission: '',
    missionApproved: false,
    skillPlan: [],
    customSkills: [],
    competencyMap: [],
  },
  subscription: {
    plan: 'free',
    status: 'none',
    promptpayId: '0812345678',
    autoRenew: true,
    currentPeriodEnd: null,
    trialEndDate: null,
    invoices: [],
  },
  vrio: [
    { id: 'vr-pc1', resource: 'Paperclip · เฟรมเวิร์ก multi-agent (CEO/CTO/CMO + Heartbeat)', note: 'โอเพนซอร์ส ลอกได้ฟรี — ตลาดมี CrewAI/AutoGen/MetaGPT เพียบ จึงไม่หายาก', v: true, r: false, i: false, o: false },
    { id: 'vr-pc2', resource: 'Paperclip · self-host บน VPS + Docker', note: 'ใครก็ deploy ได้ เป็นความสามารถพื้นฐานของตลาด', v: true, r: false, i: false, o: false },
    { id: 'vr-loc', resource: 'เรา · Localization เชิงลึก (ไทย + PromptPay + VAT/e-Tax + LINE OA)', note: 'มีคุณค่าสูงและหายากในเครื่องมือระดับโลก แต่ยังลอกได้ถ้าทุ่มทุน (กฎหมาย+ระบบไทย) → ชั่วคราว', v: true, r: true, i: false, o: true },
    { id: 'vr-mng', resource: 'เรา · Managed / Zero-DevOps (ไม่ต้องตั้งเซิร์ฟเวอร์เอง)', note: 'จำเป็น (table stakes) แต่ Vercel/Replit ทำให้ไม่หายาก', v: true, r: false, i: false, o: true },
    { id: 'vr-data', resource: 'เรา · เทมเพลต + คลังข้อมูลผลลัพธ์ SME ไทย (data/network effect)', note: 'ยิ่งใช้ยิ่งฉลาดเฉพาะตลาดไทย ลอกยาก = คูเมืองตัวจริง แต่ยังต้องจัดองค์กรเก็บเกี่ยว', v: true, r: true, i: true, o: false },
    { id: 'vr-eco', resource: 'เรา · Ecosystem ไทย (Omise/GB Prime, FlowAccount/PEAK, Shopee-Lazada, LINE)', note: 'ดีลเชื่อมต่อ = distribution moat ลอกได้แต่แพง', v: true, r: true, i: false, o: true },
    { id: 'vr-trust', resource: 'เรา · ความเชื่อใจ/แบรนด์ + PDPA + ซัพพอร์ตภาษาไทย', note: 'สร้างคุณค่าแต่ยังไม่หายากในช่วงเริ่มต้น — สะสมตามเวลา', v: true, r: false, i: false, o: true },
  ],
  marketplace: {
    feePct: 3,
    partners: [
      { id: 'mp1', name: 'Studio Saraban', category: 'การตลาด & คอนเทนต์', desc: 'ทีมครีเอทีฟผลิตคอนเทนต์ + ยิงแอดสำหรับ SME', rating: 4.8, priceFrom: 15000, location: 'กรุงเทพฯ', verified: true },
      { id: 'mp2', name: 'ไทยโออีเอ็ม แฟคทอรี่', category: 'ผลิตสินค้า OEM', desc: 'รับผลิตสินค้าความงาม/อาหารเสริม มี อย. ครบ', rating: 4.6, priceFrom: 50000, location: 'สมุทรสาคร', verified: true },
      { id: 'mp3', name: 'Speed Logistics', category: 'ขนส่ง & โลจิสติกส์', desc: 'คลังสินค้า + จัดส่งทั่วไทย เชื่อม Shopee/Lazada', rating: 4.5, priceFrom: 8000, location: 'นนทบุรี', verified: true },
      { id: 'mp4', name: 'สำนักงานบัญชี มั่นคง', category: 'บัญชี & ภาษี', desc: 'ทำบัญชี ยื่นภาษี VAT จดทะเบียนบริษัท', rating: 4.9, priceFrom: 3500, location: 'เชียงใหม่', verified: true },
      { id: 'mp5', name: 'Devhouse BKK', category: 'พัฒนาซอฟต์แวร์', desc: 'ทีมพัฒนาเว็บ/แอป เชื่อม API และระบบ AI', rating: 4.7, priceFrom: 40000, location: 'กรุงเทพฯ', verified: false },
      { id: 'mp6', name: 'ฟ้าใส ดีไซน์', category: 'ดีไซน์ & แบรนด์', desc: 'ออกแบบโลโก้ แพ็กเกจจิ้ง และ Brand Identity', rating: 4.4, priceFrom: 12000, location: 'ขอนแก่น', verified: false },
    ],
    deals: [
      { id: 'dl1', partnerId: 'mp1', title: 'แคมเปญเปิดตัวสินค้าใหม่ Q3', amount: 45000, status: 'closed' },
      { id: 'dl2', partnerId: 'mp3', title: 'เช่าคลัง + จัดส่ง 3 เดือน', amount: 24000, status: 'negotiating' },
      { id: 'dl3', partnerId: 'mp4', title: 'วางระบบบัญชี + ยื่นภาษีรายปี', amount: 18000, status: 'matched' },
    ],
  },
  roadmap: [
    { id: 'rm1', title: 'MVP Platform Launch', description: 'เปิดตัวแพลตฟอร์ม CEO AI Thailand เวอร์ชันแรก — Auth, Dashboard, VRIO', quarter: 'Q1', year: 2025, status: 'done', priority: 'must', owner: 'CTO' },
    { id: 'rm2', title: 'AI Company Module', description: 'ระบบองค์กร AI อัตโนมัติ — Org Chart, Kanban, Agent Execution', quarter: 'Q2', year: 2025, status: 'done', priority: 'must', owner: 'CTO' },
    { id: 'rm3', title: 'Business Builder (MIT 24 Steps)', description: 'wizard 24 ขั้นตอน MIT พร้อม AI วิเคราะห์แต่ละขั้นตอน', quarter: 'Q2', year: 2025, status: 'in_progress', priority: 'must', owner: 'Product' },
    { id: 'rm4', title: 'Revenue Model Automation', description: 'SEO Agent ประมวลผล Revenue Model อัตโนมัติ — LTV / COCA / K-Factor', quarter: 'Q3', year: 2025, status: 'planned', priority: 'must', owner: 'SEO' },
    { id: 'rm5', title: 'Knowledge Base per Department', description: 'คลังความรู้แยกตามแผนก — AI agents เรียนรู้จาก KB ของตัวเอง', quarter: 'Q3', year: 2025, status: 'planned', priority: 'should', owner: 'CTO' },
    { id: 'rm6', title: 'Marketplace & Partner API', description: 'เชื่อมต่อพาร์ทเนอร์ผ่าน API Marketplace — จ่ายเงิน, ประเมิน, รายงาน', quarter: 'Q4', year: 2025, status: 'planned', priority: 'should', owner: 'CEO' },
    { id: 'rm7', title: 'Multi-Workspace Enterprise', description: 'รองรับลูกค้าองค์กร — workspace แยก, RLS, billing รายทีม', quarter: 'Q4', year: 2025, status: 'planned', priority: 'nice', owner: 'CTO' },
  ],
  winStories: [
    {
      id: 'ws1',
      date: '2025-05-15',
      customerName: 'บริษัท มั่งมี จำกัด',
      category: 'efficiency',
      headlineMetric: 'ประหยัดเวลา 28 ชั่วโมง/สัปดาห์',
      situation: 'ทีมงาน 5 คนใช้เวลาส่วนใหญ่ทำรายงานและสรุปข้อมูลด้วยมือ ทุกสัปดาห์ต้องใช้เวลา ~35 ชั่วโมงสำหรับงาน admin ที่ซ้ำซ้อน ทำให้ไม่มีเวลาพัฒนาธุรกิจ',
      challenge: 'ระบบเดิมเป็น Excel หลายไฟล์ที่ไม่เชื่อมกัน ไม่มีใครในทีมที่มีทักษะ AI หรือ automation',
      actions: ['วางระบบ AI Company module — กำหนด mandate ให้ CEO, CFO, CMO agents', 'ตั้ง Kanban board สำหรับงาน recurring รายสัปดาห์', 'เชื่อม Line OA กับ AI assistant สำหรับ report auto-generation', 'ฝึกใช้ AI Research สำหรับการวิเคราะห์คู่แข่ง'],
      turningPoint: 'สัปดาห์ที่ 3: CFO agent สร้าง P&L summary อัตโนมัติ ประหยัดเวลา 12 ชั่วโมงในรอบเดียว ทีมเริ่มไว้วางใจระบบ',
      metrics: [
        { label: 'เวลา admin/สัปดาห์', before: '35 ชม.', after: '7 ชม.', change: '-80%' },
        { label: 'ค่าใช้จ่าย consultant', before: '฿25,000/เดือน', after: '฿0', change: '-100%' },
        { label: 'ความเร็วตัดสินใจ', before: '3-5 วัน', after: '< 4 ชั่วโมง', change: '+600%' },
      ],
      timeline: 'เม.ย. 2025 → ทดลองใช้ 15 วัน → เปิดใช้งานจริง → พ.ค. 2025 ผลลัพธ์ชัดเจน',
      quote: '"ก่อนหน้านี้ผมต้องนั่งทำ Excel ทุกวันจันทร์เกือบทั้งวัน ตอนนี้ระบบทำให้เสร็จในคืนวันอาทิตย์ ผมมาเจอรายงานพร้อมแล้วตอนเปิดคอม"',
      lessons: ['ลูกค้า SME ไม่ต้องการ AI ที่ซับซ้อน ต้องการ AI ที่ "ทำงานแทนได้เลย"', 'เริ่มจาก use case ที่ลูกค้าเจ็บปวดที่สุด — งาน admin ซ้ำซ้อน', 'สัปดาห์แรกสำคัญมาก — ต้องมี quick win ภายใน 7 วัน'],
      whyItMatters: 'พิสูจน์ว่า Growth plan ฿1,490/เดือน ให้ ROI ทันทีในเดือนแรก (ประหยัด ฿25,000 consultant) — ใช้เป็น case study ในหน้า Billing',
      documentedBy: 'Admin',
    },
    {
      id: 'ws2',
      date: '2025-06-01',
      customerName: 'คุณวิชัย ร้านวัสดุก่อสร้างสมบูรณ์',
      category: 'revenue',
      headlineMetric: 'เพิ่มยอดขาย 34% ใน 2 เดือน',
      situation: 'ร้านวัสดุก่อสร้างที่มีลูกค้าประจำแต่ไม่มีระบบ CRM ไม่รู้ว่าลูกค้าคนไหนซื้อซ้ำหรือเลิกซื้อ',
      challenge: 'เจ้าของดูแลทุกอย่างด้วยตัวเอง ไม่มีทีม marketing ไม่มีงบโฆษณา',
      actions: ['วิเคราะห์ Journey Map ของลูกค้าร้านวัสดุ', 'ตั้ง AI Content agent สร้าง Line OA messages รายสัปดาห์', 'ใช้ Priority Actions ติดตาม follow-up ลูกค้า top 20', 'Personas analysis ระบุ segment ผู้รับเหมา vs บุคคลทั่วไป'],
      turningPoint: 'ค้นพบว่าลูกค้ากลุ่มผู้รับเหมา (15% ของลูกค้า) สร้างรายได้ 60% — focus เฉพาะกลุ่มนี้',
      metrics: [
        { label: 'ยอดขายรายเดือน', before: '฿280,000', after: '฿375,000', change: '+34%' },
        { label: 'ลูกค้าซื้อซ้ำ', before: '45%', after: '68%', change: '+23pp' },
        { label: 'เวลา CEO/สัปดาห์', before: '60 ชม.', after: '45 ชม.', change: '-25%' },
      ],
      timeline: 'เม.ย. 2025 → วิเคราะห์ลูกค้า → พ.ค. เปิด Line OA → มิ.ย. 2025 ผลลัพธ์ชัดเจน',
      quote: '"ผมไม่เคยคิดว่าจะมีระบบแบบนี้ได้ในราคาหนึ่งพันกว่าบาท ผู้รับเหมาโทรมาหาผมเยอะขึ้น"',
      lessons: ['Pareto 80/20 ใช้ได้จริง — ลูกค้า 20% สร้างรายได้ 80%', 'Content สำหรับ B2B (ผู้รับเหมา) ต้องเน้นประโยชน์ใช้สอย ไม่ใช่ emotional', 'Line OA คือช่องทางที่ดีที่สุดสำหรับ SME ไทย'],
      whyItMatters: 'Case study สำหรับ segment "ร้านค้า/ค้าส่ง" — ROI ชัดเจนใน 60 วัน ใช้ใน sales pitch',
      documentedBy: 'Admin',
    },
  ],
  marketing: {
    monthlyBudget: 30000,
    targetLeads: 200,
    targetCAC: 2000,
    channels: [
      { id: 'ch1', name: 'Facebook Ads (SME Group)', type: 'social', budget: 8000, leadsPerMonth: 60, cpl: 133, convRate: 3.5, active: true, notes: 'กำหนดเป้ากลุ่ม เจ้าของธุรกิจ 30-50 ปี, กรุงเทพ+ปริมณฑล' },
      { id: 'ch2', name: 'Google SEO', type: 'seo', budget: 5000, leadsPerMonth: 45, cpl: 111, convRate: 4.2, active: true, notes: 'บทความ "CEO AI Thailand", "AI สำหรับ SME", "ระบบบริษัท AI"' },
      { id: 'ch3', name: 'YouTube Content', type: 'content', budget: 6000, leadsPerMonth: 40, cpl: 150, convRate: 5.0, active: true, notes: 'Case study ลูกค้า + How-to AI สำหรับธุรกิจไทย' },
      { id: 'ch4', name: 'Line OA + Broadcast', type: 'email', budget: 2000, leadsPerMonth: 30, cpl: 67, convRate: 6.0, active: true, notes: 'Broadcast รายสัปดาห์ + retargeting trial users' },
      { id: 'ch5', name: 'Google SEM', type: 'sem', budget: 6000, leadsPerMonth: 25, cpl: 240, convRate: 3.0, active: false, notes: 'Keywords: AI บริษัท, ระบบ AI SME — ราคา CPC สูง' },
      { id: 'ch6', name: 'Partner Referral', type: 'referral', budget: 3000, leadsPerMonth: 20, cpl: 150, convRate: 8.0, active: true, notes: 'บัญชี, IT Consultant แนะนำลูกค้า — commission 10%' },
    ],
    campaigns: [
      { id: 'cp1', name: 'Trial 15 วัน Launch Campaign', channelId: 'ch1', budget: 15000, startDate: '2025-07-01', endDate: '2025-07-31', goal: 'เพิ่ม trial signups 100 ราย', kpiTarget: 'CPA < ฿800', status: 'planned', result: '' },
      { id: 'cp2', name: 'YouTube Case Study Series', channelId: 'ch3', budget: 12000, startDate: '2025-06-15', endDate: '2025-08-31', goal: 'สร้าง 4 case study videos', kpiTarget: '10K views + 50 leads', status: 'active', result: 'อยู่ระหว่างถ่ายทำ video ที่ 2' },
      { id: 'cp3', name: 'SEO Content Blitz Q2', channelId: 'ch2', budget: 10000, startDate: '2025-04-01', endDate: '2025-06-30', goal: 'เขียน 20 บทความ + rank top 3', kpiTarget: 'Organic traffic +50%', status: 'done', result: 'เขียน 18 บทความ, traffic +42%' },
    ],
    goals: [
      { id: 'g1', metric: 'Trial Signups/เดือน', current: 35, target: 100, unit: 'ราย' },
      { id: 'g2', metric: 'Trial → Paid Conversion', current: 18, target: 30, unit: '%' },
      { id: 'g3', metric: 'Monthly Leads', current: 120, target: 200, unit: 'ราย' },
      { id: 'g4', metric: 'Customer Acquisition Cost', current: 3200, target: 2000, unit: '฿' },
      { id: 'g5', metric: 'Brand Awareness (YouTube)', current: 4200, target: 10000, unit: 'subscribers' },
    ],
  },
  feedback: {
    period: 'Q2 2026',
    themes: [
      { id: 'ui_ux',       name: 'UI/UX & ความง่ายใช้งาน',   impact: 3, effort: 2 },
      { id: 'ai_quality',  name: 'คุณภาพ AI Agent',           impact: 5, effort: 4 },
      { id: 'performance', name: 'ประสิทธิภาพ/ความเร็ว',      impact: 4, effort: 3 },
      { id: 'docs',        name: 'เอกสาร & คู่มือ',           impact: 3, effort: 1 },
      { id: 'pricing',     name: 'ราคา/คุณค่า',               impact: 4, effort: 2 },
      { id: 'mobile',      name: 'ประสบการณ์มือถือ',          impact: 3, effort: 3 },
    ],
    entries: [
      { id: 'fb1',  date: '2026-04-05', source: 'survey',  sentiment: 'positive', theme: 'ui_ux',       content: 'UI สวยงามและใช้งานได้ง่ายมาก ลูกค้าใหม่ก็เรียนรู้ได้เร็ว ไม่ต้องผ่านการ training', rating: 5 },
      { id: 'fb2',  date: '2026-04-12', source: 'review',  sentiment: 'positive', theme: 'ui_ux',       content: 'ออกแบบ Dashboard ได้ดีมาก ทุกอย่างอยู่ตรงที่คาดไว้ ชอบ color scheme มาก', rating: 4 },
      { id: 'fb3',  date: '2026-04-18', source: 'email',   sentiment: 'positive', theme: 'ui_ux',       content: 'ชอบ Sidebar ที่กระชับ icon ชัดเจน ประหยัดเวลานำทางเยอะมาก', rating: 4 },
      { id: 'fb4',  date: '2026-05-02', source: 'survey',  sentiment: 'positive', theme: 'ui_ux',       content: 'หน้า Customer Journey ออกแบบได้ดี เข้าใจง่าย แชร์ให้ทีมได้เลย', rating: 5 },
      { id: 'fb5',  date: '2026-05-14', source: 'social',  sentiment: 'positive', theme: 'ui_ux',       content: 'Design ดูมืออาชีพมาก เพื่อนถามว่าทำแพงมั้ย คุ้มค่ากับราคา', rating: 5 },
      { id: 'fb6',  date: '2026-05-20', source: 'survey',  sentiment: 'neutral',  theme: 'ui_ux',       content: 'ใช้งานได้ดีแต่บางหน้าต้อง scroll เยอะไปหน่อย อาจปรับ layout ได้', rating: 3 },
      { id: 'fb7',  date: '2026-06-01', source: 'support', sentiment: 'neutral',  theme: 'ui_ux',       content: 'Tab แต่ละอันมีเยอะมากจนสับสน อยากให้จัดกลุ่มให้ชัดกว่านี้', rating: 3 },
      { id: 'fb8',  date: '2026-06-10', source: 'support', sentiment: 'negative', theme: 'ui_ux',       content: 'เมนู Admin หาไม่เจอตอนแรก ไม่รู้ว่าอยู่ที่ Sidebar ต้องถามทีม', rating: 2 },
      { id: 'fb9',  date: '2026-04-08', source: 'survey',  sentiment: 'positive', theme: 'ai_quality',  content: 'AI Agent วิเคราะห์ Customer Journey ได้ตรงประเด็น ประหยัดเวลา 3 ชั่วโมง/สัปดาห์', rating: 5 },
      { id: 'fb10', date: '2026-05-11', source: 'review',  sentiment: 'positive', theme: 'ai_quality',  content: 'คำแนะนำ AI เรื่อง VRIO Analysis ดีกว่าที่คาด ส่ง board ได้เลยโดยไม่ต้องแก้มาก', rating: 4 },
      { id: 'fb11', date: '2026-04-22', source: 'email',   sentiment: 'neutral',  theme: 'ai_quality',  content: 'AI ตอบได้ดีบางครั้ง แต่บางคำถามคำตอบ generic ไปไม่ specific กับธุรกิจเรา', rating: 3 },
      { id: 'fb12', date: '2026-05-05', source: 'support', sentiment: 'negative', theme: 'ai_quality',  content: 'ขอ AI ช่วยเรื่อง pricing strategy แต่ได้คำตอบที่ไม่ตรงกับ context ธุรกิจไทย SME', rating: 2 },
      { id: 'fb13', date: '2026-05-18', source: 'survey',  sentiment: 'negative', theme: 'ai_quality',  content: 'AI ตอบผิดเรื่องสูตรคำนวณ LTV:COCA ต้องแก้ด้วยตัวเองทุกครั้ง ขาดความน่าเชื่อถือ', rating: 2 },
      { id: 'fb14', date: '2026-06-03', source: 'support', sentiment: 'negative', theme: 'ai_quality',  content: 'AI แนะนำ persona ซ้ำๆ กับที่มีอยู่แล้ว ไม่ได้ insight ใหม่เลย', rating: 2 },
      { id: 'fb15', date: '2026-06-15', source: 'social',  sentiment: 'negative', theme: 'ai_quality',  content: 'อยากให้ AI มีบริบทไทยมากกว่านี้ บางครั้งแนะนำแบบ US market ซึ่งไม่ work ที่นี่', rating: 2 },
      { id: 'fb16', date: '2026-04-10', source: 'survey',  sentiment: 'positive', theme: 'performance', content: 'โหลดหน้าต่างๆ เร็วดี ไม่ lag แม้ใช้ผ่าน 4G นอกสำนักงาน', rating: 4 },
      { id: 'fb17', date: '2026-05-07', source: 'support', sentiment: 'neutral',  theme: 'performance', content: 'บางครั้งหน้า AI Company ช้ากว่าหน้าอื่น คงเพราะโหลดข้อมูล agent เยอะ', rating: 3 },
      { id: 'fb18', date: '2026-05-25', source: 'support', sentiment: 'negative', theme: 'performance', content: 'บันทึกข้อมูลแล้ว timeout ไป 3 ครั้งในหนึ่งสัปดาห์ ต้องกรอกข้อมูลซ้ำทุกครั้ง', rating: 1 },
      { id: 'fb19', date: '2026-06-08', source: 'email',   sentiment: 'negative', theme: 'performance', content: 'Export PDF ใช้เวลานาน 30+ วินาที บางครั้ง browser แสดง error ต้อง reload', rating: 2 },
      { id: 'fb20', date: '2026-04-30', source: 'support', sentiment: 'neutral',  theme: 'docs',        content: 'มีวิดีโอสอนแต่ยังไม่ครอบคลุม feature ใหม่ เช่น Marketing Strategy และ Win Stories', rating: 3 },
      { id: 'fb21', date: '2026-05-22', source: 'support', sentiment: 'negative', theme: 'docs',        content: 'ไม่รู้วิธีตั้งค่า Supabase + AI Integration มีแต่ link ไป GitHub อ่านเองยาก', rating: 2 },
      { id: 'fb22', date: '2026-06-12', source: 'email',   sentiment: 'negative', theme: 'docs',        content: 'ต้องการคู่มือภาษาไทย step-by-step สำหรับ onboarding ใหม่ ทีมบางคนอ่าน English ไม่คล่อง', rating: 2 },
      { id: 'fb23', date: '2026-05-03', source: 'survey',  sentiment: 'positive', theme: 'pricing',     content: 'ราคา Growth ฿1,490 คุ้มมากเมื่อเทียบกับ consultant ที่เราเคยจ้าง เดือนละหลายหมื่น', rating: 5 },
      { id: 'fb24', date: '2026-06-05', source: 'review',  sentiment: 'neutral',  theme: 'pricing',     content: 'ราคารับได้แต่อยากได้ annual plan ที่ถูกกว่ารายเดือน ลด churn ได้ด้วย', rating: 3 },
      { id: 'fb25', date: '2026-05-28', source: 'survey',  sentiment: 'negative', theme: 'mobile',      content: 'บนมือถือ Sidebar ทับเนื้อหา ต้องปิดทุกครั้ง ถ้าอยู่นอก office ใช้งานยากมาก', rating: 1 },
      { id: 'fb26', date: '2026-06-18', source: 'social',  sentiment: 'negative', theme: 'mobile',      content: 'บน iPad ขนาดเล็ก table columns หายออกหน้าจอ ต้อง scroll ขวางอยู่ตลอดเวลา', rating: 2 },
    ],
  },
  gtmAuditChecks: [false, false, false, false, false, false, false],
};
